version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - frontend
    ports:
      - "8080:80"
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8081:8080"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
