services:
  app:
    image: php:8.2-fpm
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - symfony_network

  webserver:
    image: nginx:stable
    container_name: symfony_webserver
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - symfony_network

  database:
      image: mysql:8.0
      container_name: symfony_db
      environment:
        PMA_HOST: symfony_db
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql  # ← Stocke les bases de données et relations internes
      networks:
        - symfony_network

  adminer:
    image: adminer
    container_name: symfony_adminer
    restart: always
    ports:
      - "8081:8080" # Adminer sera accessible sur http://localhost:8081
    depends_on:
      - database
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8082:80" # phpMyAdmin sera accessible sur http://localhost:8082
    environment:
      PMA_HOST: symfony_db
      MYSQL_ROOT_PASSWORD: root
      PMA_PMADB: phpmyadmin
      PMA_CONTROLUSER: symfony
      PMA_CONTROLPASS: symfony
    depends_on:
      - database
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data: # Déclaration du volume nommé pour la persistance des données
  phpmyadmin_data: